/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CropHealthStats {
  'totalCropsMonitored' : bigint,
  'healthyCount' : bigint,
  'lastUpdatedTimestamp' : Time,
  'infectedCount' : bigint,
}
export interface DeviceStatus {
  'fieldCoveragePercentage' : bigint,
  'lastScanTimestamp' : Time,
  'batteryPercentage' : bigint,
  'operationalStatus' : string,
}
export interface DiseaseDetection {
  'id' : bigint,
  'detectedTimestamp' : Time,
  'recommendedTreatment' : string,
  'severityLevel' : string,
  'affectedCrop' : string,
  'description' : string,
  'diseaseName' : string,
}
export interface DiseaseLibrary {
  'id' : bigint,
  'symptomsDescription' : string,
  'affectedCropType' : string,
  'diseaseName' : string,
  'treatmentRecommendations' : string,
  'preventionTips' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllDetections' : ActorMethod<[], Array<DiseaseDetection>>,
  'getCropHealthStats' : ActorMethod<[], CropHealthStats>,
  'getDeviceStatus' : ActorMethod<[], DeviceStatus>,
  'getDiseaseLibrary' : ActorMethod<[], Array<DiseaseLibrary>>,
  'seedData' : ActorMethod<[], undefined>,
  'updateCropHealthStats' : ActorMethod<
    [bigint, bigint, bigint, Time],
    undefined
  >,
  'updateDeviceStatus' : ActorMethod<[bigint, string, Time, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];