/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const DiseaseDetection = IDL.Record({
  'id' : IDL.Nat,
  'detectedTimestamp' : Time,
  'recommendedTreatment' : IDL.Text,
  'severityLevel' : IDL.Text,
  'affectedCrop' : IDL.Text,
  'description' : IDL.Text,
  'diseaseName' : IDL.Text,
});
export const CropHealthStats = IDL.Record({
  'totalCropsMonitored' : IDL.Nat,
  'healthyCount' : IDL.Nat,
  'lastUpdatedTimestamp' : Time,
  'infectedCount' : IDL.Nat,
});
export const DeviceStatus = IDL.Record({
  'fieldCoveragePercentage' : IDL.Nat,
  'lastScanTimestamp' : Time,
  'batteryPercentage' : IDL.Nat,
  'operationalStatus' : IDL.Text,
});
export const DiseaseLibrary = IDL.Record({
  'id' : IDL.Nat,
  'symptomsDescription' : IDL.Text,
  'affectedCropType' : IDL.Text,
  'diseaseName' : IDL.Text,
  'treatmentRecommendations' : IDL.Text,
  'preventionTips' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllDetections' : IDL.Func([], [IDL.Vec(DiseaseDetection)], ['query']),
  'getCropHealthStats' : IDL.Func([], [CropHealthStats], ['query']),
  'getDeviceStatus' : IDL.Func([], [DeviceStatus], ['query']),
  'getDiseaseLibrary' : IDL.Func([], [IDL.Vec(DiseaseLibrary)], ['query']),
  'seedData' : IDL.Func([], [], []),
  'updateCropHealthStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, Time], [], []),
  'updateDeviceStatus' : IDL.Func([IDL.Nat, IDL.Text, Time, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const DiseaseDetection = IDL.Record({
    'id' : IDL.Nat,
    'detectedTimestamp' : Time,
    'recommendedTreatment' : IDL.Text,
    'severityLevel' : IDL.Text,
    'affectedCrop' : IDL.Text,
    'description' : IDL.Text,
    'diseaseName' : IDL.Text,
  });
  const CropHealthStats = IDL.Record({
    'totalCropsMonitored' : IDL.Nat,
    'healthyCount' : IDL.Nat,
    'lastUpdatedTimestamp' : Time,
    'infectedCount' : IDL.Nat,
  });
  const DeviceStatus = IDL.Record({
    'fieldCoveragePercentage' : IDL.Nat,
    'lastScanTimestamp' : Time,
    'batteryPercentage' : IDL.Nat,
    'operationalStatus' : IDL.Text,
  });
  const DiseaseLibrary = IDL.Record({
    'id' : IDL.Nat,
    'symptomsDescription' : IDL.Text,
    'affectedCropType' : IDL.Text,
    'diseaseName' : IDL.Text,
    'treatmentRecommendations' : IDL.Text,
    'preventionTips' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllDetections' : IDL.Func([], [IDL.Vec(DiseaseDetection)], ['query']),
    'getCropHealthStats' : IDL.Func([], [CropHealthStats], ['query']),
    'getDeviceStatus' : IDL.Func([], [DeviceStatus], ['query']),
    'getDiseaseLibrary' : IDL.Func([], [IDL.Vec(DiseaseLibrary)], ['query']),
    'seedData' : IDL.Func([], [], []),
    'updateCropHealthStats' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, Time],
        [],
        [],
      ),
    'updateDeviceStatus' : IDL.Func([IDL.Nat, IDL.Text, Time, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };